// Code generated by "stringer -type=Severity"; DO NOT EDIT.

package sperr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error-69]
}

const _Severity_name = "Error"

var _Severity_index = [...]uint8{0, 5}

func (i Severity) String() string {
	i -= 69
	if i < 0 || i >= Severity(len(_Severity_index)-1) {
		return "Severity(" + strconv.FormatInt(int64(i+69), 10) + ")"
	}
	return _Severity_name[_Severity_index[i]:_Severity_index[i+1]]
}
