// Code generated by "stringer -type=EnvVarType"; DO NOT EDIT.

package cmdconfig

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[String-0]
	_ = x[Int-1]
	_ = x[Bool-2]
}

const _EnvVarType_name = "StringIntBool"

var _EnvVarType_index = [...]uint8{0, 6, 9, 13}

func (i EnvVarType) String() string {
	if i < 0 || i >= EnvVarType(len(_EnvVarType_index)-1) {
		return "EnvVarType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnvVarType_name[_EnvVarType_index[i]:_EnvVarType_index[i+1]]
}
