# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    id: "steampipe"
    binary:
      'steampipe'
archives:
  - files:
    - none*
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: linux
      format: tar.gz

checksum:
  name_template: 'checksums.txt'
release:
  # Visit your project's GitHub Releases page to publish this release.
  draft: true
changelog:
  skip: true