# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    id: "steampipe"
    binary:
      'steampipe'
archives:
  - files:
    - none*
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: linux
      format: tar.gz

nfpms:
  - id: "steampipe"
    builds: ['steampipe']
    formats:
      - deb
      - rpm
    vendor: "steampipe.io"
    homepage: "https://steampipe.io/"
    maintainer: "Turbot Support <help@turbot.com>"
    description: "Use SQL to instantly query your cloud services (AWS, Azure, GCP and more). Open source CLI. No DB required."
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    rpm:
      summary: "Use SQL to instantly query your cloud services (AWS, Azure, GCP and more). Open source CLI. No DB required."

# it is necessary to specify the name_template of the snapshot, or else the snapshot gets created with
# two dash(-) which results in a 500 error while downloading
snapshot:
  name_template: '{{ .Version }}'

# snapcrafts:
#   - id: "steampipe"
#     builds: ['steampipe']
#     description: "Use SQL to instantly query your cloud services (AWS, Azure, GCP and more). Open source CLI. No DB required."
#     summary: "Snap package"
#     name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
release:
  # Visit your project's GitHub Releases page to publish this release.
  draft: true
changelog:
  skip: true
