package parse

import (
	"strings"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/turbot/steampipe/steampipeconfig/modconfig"
)

func GetMetadataForParsedResource(resourceName string, block *hcl.Block, fileData map[string][]byte, mod *modconfig.Mod) (*modconfig.ResourceMetadata, error) {
	body := block.Body.(*hclsyntax.Body)

	// convert the name into a short name
	parsedName, err := modconfig.ParseResourceName(resourceName)
	if err != nil {
		return nil, err
	}
	m := &modconfig.ResourceMetadata{
		ResourceName:     parsedName.Name,
		FileName:         body.SrcRange.Filename,
		StartLineNumber:  body.SrcRange.Start.Line,
		EndLineNumber:    body.SrcRange.End.Line,
		IsAutoGenerated:  false,
		SourceDefinition: getSourceDefinition(body.SrcRange, fileData),
	}
	// update the 'ModName' and 'ModShortName' fields
	m.SetMod(mod)
	return m, nil
}

func getSourceDefinition(sourceRange hcl.Range, fileData map[string][]byte) string {
	filename := sourceRange.Filename
	fileBytes, ok := fileData[filename]
	if !ok {
		return ""
	}

	source := strings.Join(
		strings.Split(string(fileBytes), "\n")[sourceRange.Start.Line-1:sourceRange.End.Line], "\n")
	return source
}
