package parse

import (
	"strings"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/turbot/steampipe/steampipeconfig/modconfig"
)

func GetMetadataForParsedResource(resourceName string, block *hcl.Block, fileData map[string][]byte, mod *modconfig.Mod) *modconfig.ResourceMetadata {
	body := block.Body.(*hclsyntax.Body)

	m := &modconfig.ResourceMetadata{
		ResourceName:     resourceName,
		FileName:         body.SrcRange.Filename,
		StartLineNumber:  body.SrcRange.Start.Line,
		EndLineNumber:    body.SrcRange.End.Line,
		IsAutoGenerated:  false,
		SourceDefinition: getSourceDefinition(body.SrcRange, fileData),
	}
	// update the 'ModName' and 'ModShortName' fields
	m.SetMod(mod)
	return m
}

func getSourceDefinition(sourceRange hcl.Range, fileData map[string][]byte) string {
	filename := sourceRange.Filename
	fileBytes, ok := fileData[filename]
	if !ok {
		return ""
	}

	source := strings.Join(
		strings.Split(string(fileBytes), "\n")[sourceRange.Start.Line-1:sourceRange.End.Line], "\n")
	return source
}
