package modconfig

import "github.com/hashicorp/hcl/v2"

// ReflectionData :: additional data we collect about each resource to populate the reflection tables
type ReflectionData struct {
	ModName          string
	ResourceName     string
	Range            hcl.Range
	IsAutoGenerated  bool
	SourceDefinition string
}
