package modconfig

// ReflectionDataItem :: a mod resource which supports reflection data
type ReflectionDataItem interface {
	GetCoreReflectionData() *CoreReflectionData
}

// CoreReflectionData :: additional data we collect about each resource to populate the reflection tables
type CoreReflectionData struct {
	ResourceName     string `column:"resource_name" column_type:"varchar(40)"`
	ModName          string `column:"mod_name" column_type:"varchar(40)"`
	FileName         string `column:"file_name" column_type:"text"`
	StartLineNumber  int    `column:"start_line_number" column_type:"integer"`
	EndLineNumber    int    `column:"end_line_number" column_type:"integer"`
	IsAutoGenerated  bool   `column:"auto_generated" column_type:"bool"`
	SourceDefinition string `column:"source_definition" column_type:"text"`
	Mod              *Mod
}

// TODO ADD PATH ltree
