import Chart from "../../charts/Chart";
import Primitive from "../../Primitive";
import { ColorGenerator } from "../../../../utils/color";

const buildOptions = (data) => {
  if (!data) {
    return null;
  }
  const colorGenerator = new ColorGenerator(24, 4);
  const builtData = [];
  const categories = {};
  const usedIds = {};
  const objectData = data.slice(1).map((dataRow) => {
    const row = {};
    for (let i = 0; i < data[0].length; i++) {
      const value = data[0][i];
      row[value] = dataRow[i];
    }

    if (row.category && !categories[row.category]) {
      categories[row.category] = { color: colorGenerator.nextColor().hex };
    }

    if (!usedIds[row.id]) {
      builtData.push(row);
      usedIds[row.id] = true;
    }
    return row;
  });
  const edges = [];
  for (const d of objectData) {
    // TODO remove <null> after Kai fixes base64 issue and removes col string conversion
    if (d.parent === null || d.parent === "<null>") {
      d.parent = null;
      continue;
    }
    edges.push({ source: d.parent, target: d.id, value: 0.01 });
  }
  const options = {
    //tooltip: {
    //    trigger: 'item'
    //},
    // tooltip: {},
    animationDuration: 1500,
    animationEasingUpdate: "quinticInOut",
    series: {
      type: "graph",
      layout: "force",
      animation: false,
      roam: true,
      draggable: true,
      force: {
        //initLayout: "circular",
        gravity: 0.01,
        repulsion: 400,
        edgeLength: 300,
      },
      lineStyle: {
        curveness: 0.1,
        //autoCurveness: true,
      },
      label: { show: true, color: "white" },
      data: builtData,
      links: edges,
      categories: Object.entries(categories).map(([category, info]) => ({
        name: category,
        symbol: "rect",
        symbolSize: [160, 40],
        itemStyle: { color: info.color },
      })),
    },
  };
  return options;
};

const Graph = ({ data, error }) => {
  const options = buildOptions(data);
  // const options = {
  //   title: {
  //     text: "Les Miserables",
  //     subtext: "Default layout",
  //     top: "bottom",
  //     left: "right",
  //   },
  //   tooltip: {},
  //   legend: [
  //     {
  //       data: [
  //         "类目0",
  //         "类目1",
  //         "类目2",
  //         "类目3",
  //         "类目4",
  //         "类目5",
  //         "类目6",
  //         "类目7",
  //         "类目8",
  //       ],
  //     },
  //   ],
  //   animationDuration: 1500,
  //   animationEasingUpdate: "quinticInOut",
  //   series: [
  //     {
  //       name: "Les Miserables",
  //       type: "graph",
  //       layout: "none",
  //       data: [
  //         {
  //           id: "0",
  //           name: "Myriel",
  //           symbolSize: 19.12381,
  //           x: -53.365552,
  //           y: 59.93808,
  //           value: 28.685715,
  //           category: 0,
  //         },
  //         {
  //           id: "1",
  //           name: "Napoleon",
  //           symbolSize: 2.6666666666666665,
  //           x: -83.616688,
  //           y: 89.37706,
  //           value: 4,
  //           category: 0,
  //         },
  //         {
  //           id: "2",
  //           name: "MlleBaptistine",
  //           symbolSize: 6.323809333333333,
  //           x: -42.552713999999995,
  //           y: 49.058352,
  //           value: 9.485714,
  //           category: 1,
  //         },
  //         {
  //           id: "3",
  //           name: "MmeMagloire",
  //           symbolSize: 6.323809333333333,
  //           x: -48.564808,
  //           y: 47.052566,
  //           value: 9.485714,
  //           category: 1,
  //         },
  //         {
  //           id: "4",
  //           name: "CountessDeLo",
  //           symbolSize: 2.6666666666666665,
  //           x: -75.860772,
  //           y: 85.812848,
  //           value: 4,
  //           category: 0,
  //         },
  //         {
  //           id: "5",
  //           name: "Geborand",
  //           symbolSize: 2.6666666666666665,
  //           x: -83.452674,
  //           y: 81.20701199999999,
  //           value: 4,
  //           category: 0,
  //         },
  //         {
  //           id: "6",
  //           name: "Champtercier",
  //           symbolSize: 2.6666666666666665,
  //           x: -66.52024,
  //           y: 97.033948,
  //           value: 4,
  //           category: 0,
  //         },
  //         {
  //           id: "7",
  //           name: "Cravatte",
  //           symbolSize: 2.6666666666666665,
  //           x: -76.539136,
  //           y: 95.018226,
  //           value: 4,
  //           category: 0,
  //         },
  //         {
  //           id: "8",
  //           name: "Count",
  //           symbolSize: 2.6666666666666665,
  //           x: -64.0768,
  //           y: 77.43465,
  //           value: 4,
  //           category: 0,
  //         },
  //         {
  //           id: "9",
  //           name: "OldMan",
  //           symbolSize: 2.6666666666666665,
  //           x: -68.879664,
  //           y: 90.233544,
  //           value: 4,
  //           category: 0,
  //         },
  //         {
  //           id: "10",
  //           name: "Labarre",
  //           symbolSize: 2.6666666666666665,
  //           x: -17.868214000000002,
  //           y: 46.912256,
  //           value: 4,
  //           category: 1,
  //         },
  //         {
  //           id: "11",
  //           name: "Valjean",
  //           symbolSize: 66.66666666666667,
  //           x: -17.586058,
  //           y: -1.3624113,
  //           value: 100,
  //           category: 1,
  //         },
  //         {
  //           id: "12",
  //           name: "Marguerite",
  //           symbolSize: 4.495239333333333,
  //           x: -67.955816,
  //           y: -36.938278000000004,
  //           value: 6.742859,
  //           category: 1,
  //         },
  //         {
  //           id: "13",
  //           name: "MmeDeR",
  //           symbolSize: 2.6666666666666665,
  //           x: -38.862626,
  //           y: 35.710602,
  //           value: 4,
  //           category: 1,
  //         },
  //         {
  //           id: "14",
  //           name: "Isabeau",
  //           symbolSize: 2.6666666666666665,
  //           x: -31.610336,
  //           y: 40.399536,
  //           value: 4,
  //           category: 1,
  //         },
  //         {
  //           id: "15",
  //           name: "Gervais",
  //           symbolSize: 2.6666666666666665,
  //           x: -25.5403092,
  //           y: 48.510114,
  //           value: 4,
  //           category: 1,
  //         },
  //         {
  //           id: "16",
  //           name: "Tholomyes",
  //           symbolSize: 17.295237333333333,
  //           x: -77.04452,
  //           y: -78.71144000000001,
  //           value: 25.942856,
  //           category: 2,
  //         },
  //         {
  //           id: "17",
  //           name: "Listolier",
  //           symbolSize: 13.638097333333334,
  //           x: -103.311768,
  //           y: -78.79795,
  //           value: 20.457146,
  //           category: 2,
  //         },
  //         {
  //           id: "18",
  //           name: "Fameuil",
  //           symbolSize: 13.638097333333334,
  //           x: -92.958764,
  //           y: -98.71588799999999,
  //           value: 20.457146,
  //           category: 2,
  //         },
  //         {
  //           id: "19",
  //           name: "Blacheville",
  //           symbolSize: 13.638097333333334,
  //           x: -103.03248,
  //           y: -91.39782,
  //           value: 20.457146,
  //           category: 2,
  //         },
  //         {
  //           id: "20",
  //           name: "Favourite",
  //           symbolSize: 13.638097333333334,
  //           x: -81.624244,
  //           y: -92.90096,
  //           value: 20.457146,
  //           category: 2,
  //         },
  //         {
  //           id: "21",
  //           name: "Dahlia",
  //           symbolSize: 13.638097333333334,
  //           x: -91.288226,
  //           y: -85.026606,
  //           value: 20.457146,
  //           category: 2,
  //         },
  //         {
  //           id: "22",
  //           name: "Zephine",
  //           symbolSize: 13.638097333333334,
  //           x: -91.82214,
  //           y: -72.50266,
  //           value: 20.457146,
  //           category: 2,
  //         },
  //         {
  //           id: "23",
  //           name: "Fantine",
  //           symbolSize: 28.266666666666666,
  //           x: -62.685572,
  //           y: -57.889606,
  //           value: 42.4,
  //           category: 2,
  //         },
  //         {
  //           id: "24",
  //           name: "MmeThenardier",
  //           symbolSize: 20.95238266666667,
  //           x: 0.9262679199999999,
  //           y: -54.77034,
  //           value: 31.428574,
  //           category: 7,
  //         },
  //         {
  //           id: "25",
  //           name: "Thenardier",
  //           symbolSize: 30.095235333333335,
  //           x: 16.56165,
  //           y: -40.622879999999995,
  //           value: 45.142853,
  //           category: 7,
  //         },
  //         {
  //           id: "26",
  //           name: "Cosette",
  //           symbolSize: 20.95238266666667,
  //           x: 15.729292000000001,
  //           y: -6.3025494,
  //           value: 31.428574,
  //           category: 6,
  //         },
  //         {
  //           id: "27",
  //           name: "Javert",
  //           symbolSize: 31.923806666666668,
  //           x: -16.292148,
  //           y: -40.840408000000004,
  //           value: 47.88571,
  //           category: 7,
  //         },
  //         {
  //           id: "28",
  //           name: "Fauchelevent",
  //           symbolSize: 8.152382000000001,
  //           x: -45.147968,
  //           y: 16.483262,
  //           value: 12.228573,
  //           category: 4,
  //         },
  //         {
  //           id: "29",
  //           name: "Bamatabois",
  //           symbolSize: 15.466666666666667,
  //           x: -77.13683999999999,
  //           y: -4.0413372,
  //           value: 23.2,
  //           category: 3,
  //         },
  //         {
  //           id: "30",
  //           name: "Perpetue",
  //           symbolSize: 4.495239333333333,
  //           x: -80.784894,
  //           y: -39.539646,
  //           value: 6.742859,
  //           category: 2,
  //         },
  //         {
  //           id: "31",
  //           name: "Simplice",
  //           symbolSize: 8.152382000000001,
  //           x: -56.28506,
  //           y: -31.690274,
  //           value: 12.228573,
  //           category: 2,
  //         },
  //         {
  //           id: "32",
  //           name: "Scaufflaire",
  //           symbolSize: 2.6666666666666665,
  //           x: -24.482696,
  //           y: 42.075006,
  //           value: 4,
  //           category: 1,
  //         },
  //         {
  //           id: "33",
  //           name: "Woman1",
  //           symbolSize: 4.495239333333333,
  //           x: -46.92002,
  //           y: -22.630134,
  //           value: 6.742859,
  //           category: 1,
  //         },
  //         {
  //           id: "34",
  //           name: "Judge",
  //           symbolSize: 11.809524666666666,
  //           x: -77.56983,
  //           y: 11.74118,
  //           value: 17.714287,
  //           category: 3,
  //         },
  //         {
  //           id: "35",
  //           name: "Champmathieu",
  //           symbolSize: 11.809524666666666,
  //           x: -67.64614,
  //           y: 17.49681,
  //           value: 17.714287,
  //           category: 3,
  //         },
  //         {
  //           id: "36",
  //           name: "Brevet",
  //           symbolSize: 11.809524666666666,
  //           x: -90.653748,
  //           y: 11.789296,
  //           value: 17.714287,
  //           category: 3,
  //         },
  //         {
  //           id: "37",
  //           name: "Chenildieu",
  //           symbolSize: 11.809524666666666,
  //           x: -77.28980800000001,
  //           y: 28.011874,
  //           value: 17.714287,
  //           category: 3,
  //         },
  //         {
  //           id: "38",
  //           name: "Cochepaille",
  //           symbolSize: 11.809524666666666,
  //           x: -89.35752,
  //           y: 24.676009999999998,
  //           value: 17.714287,
  //           category: 3,
  //         },
  //         {
  //           id: "39",
  //           name: "Pontmercy",
  //           symbolSize: 6.323809333333333,
  //           x: 67.299476,
  //           y: -53.911828,
  //           value: 9.485714,
  //           category: 6,
  //         },
  //         {
  //           id: "40",
  //           name: "Boulatruelle",
  //           symbolSize: 2.6666666666666665,
  //           x: 5.8375686,
  //           y: -92.026264,
  //           value: 4,
  //           category: 7,
  //         },
  //         {
  //           id: "41",
  //           name: "Eponine",
  //           symbolSize: 20.95238266666667,
  //           x: 47.673394,
  //           y: -42.001852,
  //           value: 31.428574,
  //           category: 7,
  //         },
  //         {
  //           id: "42",
  //           name: "Anzelma",
  //           symbolSize: 6.323809333333333,
  //           x: 37.939026,
  //           y: -69.301324,
  //           value: 9.485714,
  //           category: 7,
  //         },
  //         {
  //           id: "43",
  //           name: "Woman2",
  //           symbolSize: 6.323809333333333,
  //           x: -37.400836,
  //           y: -29.005326000000004,
  //           value: 9.485714,
  //           category: 6,
  //         },
  //         {
  //           id: "44",
  //           name: "MotherInnocent",
  //           symbolSize: 4.495239333333333,
  //           x: -50.599042,
  //           y: 25.975098000000003,
  //           value: 6.742859,
  //           category: 4,
  //         },
  //         {
  //           id: "45",
  //           name: "Gribier",
  //           symbolSize: 2.6666666666666665,
  //           x: -59.215869999999995,
  //           y: 32.623928,
  //           value: 4,
  //           category: 4,
  //         },
  //         {
  //           id: "46",
  //           name: "Jondrette",
  //           symbolSize: 2.6666666666666665,
  //           x: 110.06402,
  //           y: 104.48062,
  //           value: 4,
  //           category: 5,
  //         },
  //         {
  //           id: "47",
  //           name: "MmeBurgon",
  //           symbolSize: 4.495239333333333,
  //           x: 97.62707,
  //           y: 71.37146,
  //           value: 6.742859,
  //           category: 5,
  //         },
  //         {
  //           id: "48",
  //           name: "Gavroche",
  //           symbolSize: 41.06667066666667,
  //           x: 77.579144,
  //           y: 22.0924652,
  //           value: 61.600006,
  //           category: 8,
  //         },
  //         {
  //           id: "49",
  //           name: "Gillenormand",
  //           symbolSize: 13.638097333333334,
  //           x: 25.296619999999997,
  //           y: 13.621243999999999,
  //           value: 20.457146,
  //           category: 6,
  //         },
  //         {
  //           id: "50",
  //           name: "Magnon",
  //           symbolSize: 4.495239333333333,
  //           x: 25.41473,
  //           y: -22.611846,
  //           value: 6.742859,
  //           category: 6,
  //         },
  //         {
  //           id: "51",
  //           name: "MlleGillenormand",
  //           symbolSize: 13.638097333333334,
  //           x: 32.527118,
  //           y: 23.531299999999998,
  //           value: 20.457146,
  //           category: 6,
  //         },
  //         {
  //           id: "52",
  //           name: "MmePontmercy",
  //           symbolSize: 4.495239333333333,
  //           x: 70.73283,
  //           y: -41.17833,
  //           value: 6.742859,
  //           category: 6,
  //         },
  //         {
  //           id: "53",
  //           name: "MlleVaubois",
  //           symbolSize: 2.6666666666666665,
  //           x: 33.087878,
  //           y: 67.95472,
  //           value: 4,
  //           category: 6,
  //         },
  //         {
  //           id: "54",
  //           name: "LtGillenormand",
  //           symbolSize: 8.152382000000001,
  //           x: 27.538695999999998,
  //           y: 39.221379999999996,
  //           value: 12.228573,
  //           category: 6,
  //         },
  //         {
  //           id: "55",
  //           name: "Marius",
  //           symbolSize: 35.58095333333333,
  //           x: 41.289373999999995,
  //           y: -2.7610821999999997,
  //           value: 53.37143,
  //           category: 6,
  //         },
  //         {
  //           id: "56",
  //           name: "BaronessT",
  //           symbolSize: 4.495239333333333,
  //           x: 38.965986,
  //           y: 44.956072,
  //           value: 6.742859,
  //           category: 6,
  //         },
  //         {
  //           id: "57",
  //           name: "Mabeuf",
  //           symbolSize: 20.95238266666667,
  //           x: 119.53236,
  //           y: 27.036962,
  //           value: 31.428574,
  //           category: 8,
  //         },
  //         {
  //           id: "58",
  //           name: "Enjolras",
  //           symbolSize: 28.266666666666666,
  //           x: 71.156732,
  //           y: -14.976490799999999,
  //           value: 42.4,
  //           category: 8,
  //         },
  //         {
  //           id: "59",
  //           name: "Combeferre",
  //           symbolSize: 20.95238266666667,
  //           x: 103.05922000000001,
  //           y: -9.2335128,
  //           value: 31.428574,
  //           category: 8,
  //         },
  //         {
  //           id: "60",
  //           name: "Prouvaire",
  //           symbolSize: 17.295237333333333,
  //           x: 122.85857000000001,
  //           y: -13.86208,
  //           value: 25.942856,
  //           category: 8,
  //         },
  //         {
  //           id: "61",
  //           name: "Feuilly",
  //           symbolSize: 20.95238266666667,
  //           x: 110.03833999999999,
  //           y: -25.635073999999996,
  //           value: 31.428574,
  //           category: 8,
  //         },
  //         {
  //           id: "62",
  //           name: "Courfeyrac",
  //           symbolSize: 24.609526666666667,
  //           x: 87.23436799999999,
  //           y: -2.5457365,
  //           value: 36.91429,
  //           category: 8,
  //         },
  //         {
  //           id: "63",
  //           name: "Bahorel",
  //           symbolSize: 22.780953333333333,
  //           x: 120.51044999999999,
  //           y: 3.2842854000000004,
  //           value: 34.17143,
  //           category: 8,
  //         },
  //         {
  //           id: "64",
  //           name: "Bossuet",
  //           symbolSize: 24.609526666666667,
  //           x: 91.16391,
  //           y: -23.091652,
  //           value: 36.91429,
  //           category: 8,
  //         },
  //         {
  //           id: "65",
  //           name: "Joly",
  //           symbolSize: 22.780953333333333,
  //           x: 103.281568,
  //           y: 9.4484466,
  //           value: 34.17143,
  //           category: 8,
  //         },
  //         {
  //           id: "66",
  //           name: "Grantaire",
  //           symbolSize: 19.12381,
  //           x: 129.28626,
  //           y: -30.212662,
  //           value: 28.685715,
  //           category: 8,
  //         },
  //         {
  //           id: "67",
  //           name: "MotherPlutarch",
  //           symbolSize: 2.6666666666666665,
  //           x: 133.79136,
  //           y: 40.930976,
  //           value: 4,
  //           category: 8,
  //         },
  //         {
  //           id: "68",
  //           name: "Gueulemer",
  //           symbolSize: 19.12381,
  //           x: 15.69598,
  //           y: -69.430292,
  //           value: 28.685715,
  //           category: 7,
  //         },
  //         {
  //           id: "69",
  //           name: "Babet",
  //           symbolSize: 19.12381,
  //           x: 30.071918,
  //           y: -59.701594,
  //           value: 28.685715,
  //           category: 7,
  //         },
  //         {
  //           id: "70",
  //           name: "Claquesous",
  //           symbolSize: 19.12381,
  //           x: 27.47434,
  //           y: -82.05618,
  //           value: 28.685715,
  //           category: 7,
  //         },
  //         {
  //           id: "71",
  //           name: "Montparnasse",
  //           symbolSize: 17.295237333333333,
  //           x: 46.975494,
  //           y: -80.171966,
  //           value: 25.942856,
  //           category: 7,
  //         },
  //         {
  //           id: "72",
  //           name: "Toussaint",
  //           symbolSize: 6.323809333333333,
  //           x: 8.1884506,
  //           y: 22.756543999999998,
  //           value: 9.485714,
  //           category: 1,
  //         },
  //         {
  //           id: "73",
  //           name: "Child1",
  //           symbolSize: 4.495239333333333,
  //           x: 87.5878,
  //           y: 58.316468,
  //           value: 6.742859,
  //           category: 8,
  //         },
  //         {
  //           id: "74",
  //           name: "Child2",
  //           symbolSize: 4.495239333333333,
  //           x: 93.209844,
  //           y: 56.67211999999999,
  //           value: 6.742859,
  //           category: 8,
  //         },
  //         {
  //           id: "75",
  //           name: "Brujon",
  //           symbolSize: 13.638097333333334,
  //           x: 47.758728000000005,
  //           y: -62.812689999999996,
  //           value: 20.457146,
  //           category: 7,
  //         },
  //         {
  //           id: "76",
  //           name: "MmeHucheloup",
  //           symbolSize: 13.638097333333334,
  //           x: 142.43670600000002,
  //           y: 0.9626298999999999,
  //           value: 20.457146,
  //           category: 8,
  //         },
  //       ],
  //       links: [
  //         {
  //           id: "0",
  //           type: "1",
  //           target: "0",
  //         },
  //         {
  //           id: "1",
  //           type: "2",
  //           target: "0",
  //         },
  //         {
  //           id: "2",
  //           type: "3",
  //           target: "0",
  //         },
  //         {
  //           id: "3",
  //           type: "3",
  //           target: "2",
  //         },
  //         {
  //           id: "4",
  //           type: "4",
  //           target: "0",
  //         },
  //         {
  //           id: "5",
  //           type: "5",
  //           target: "0",
  //         },
  //         {
  //           id: "6",
  //           type: "6",
  //           target: "0",
  //         },
  //         {
  //           id: "7",
  //           type: "7",
  //           target: "0",
  //         },
  //         {
  //           id: "8",
  //           type: "8",
  //           target: "0",
  //         },
  //         {
  //           id: "9",
  //           type: "9",
  //           target: "0",
  //         },
  //         {
  //           id: "13",
  //           type: "11",
  //           target: "0",
  //         },
  //         {
  //           id: null,
  //           type: "11",
  //           target: "2",
  //         },
  //         {
  //           id: "11",
  //           type: "11",
  //           target: "3",
  //         },
  //         {
  //           id: "10",
  //           type: "11",
  //           target: "10",
  //         },
  //         {
  //           id: "14",
  //           type: "12",
  //           target: "11",
  //         },
  //         {
  //           id: "15",
  //           type: "13",
  //           target: "11",
  //         },
  //         {
  //           id: "16",
  //           type: "14",
  //           target: "11",
  //         },
  //         {
  //           id: "17",
  //           type: "15",
  //           target: "11",
  //         },
  //         {
  //           id: "18",
  //           type: "17",
  //           target: "16",
  //         },
  //         {
  //           id: "19",
  //           type: "18",
  //           target: "16",
  //         },
  //         {
  //           id: "20",
  //           type: "18",
  //           target: "17",
  //         },
  //         {
  //           id: "21",
  //           type: "19",
  //           target: "16",
  //         },
  //         {
  //           id: "22",
  //           type: "19",
  //           target: "17",
  //         },
  //         {
  //           id: "23",
  //           type: "19",
  //           target: "18",
  //         },
  //         {
  //           id: "24",
  //           type: "20",
  //           target: "16",
  //         },
  //         {
  //           id: "25",
  //           type: "20",
  //           target: "17",
  //         },
  //         {
  //           id: "26",
  //           type: "20",
  //           target: "18",
  //         },
  //         {
  //           id: "27",
  //           type: "20",
  //           target: "19",
  //         },
  //         {
  //           id: "28",
  //           type: "21",
  //           target: "16",
  //         },
  //         {
  //           id: "29",
  //           type: "21",
  //           target: "17",
  //         },
  //         {
  //           id: "30",
  //           type: "21",
  //           target: "18",
  //         },
  //         {
  //           id: "31",
  //           type: "21",
  //           target: "19",
  //         },
  //         {
  //           id: "32",
  //           type: "21",
  //           target: "20",
  //         },
  //         {
  //           id: "33",
  //           type: "22",
  //           target: "16",
  //         },
  //         {
  //           id: "34",
  //           type: "22",
  //           target: "17",
  //         },
  //         {
  //           id: "35",
  //           type: "22",
  //           target: "18",
  //         },
  //         {
  //           id: "36",
  //           type: "22",
  //           target: "19",
  //         },
  //         {
  //           id: "37",
  //           type: "22",
  //           target: "20",
  //         },
  //         {
  //           id: "38",
  //           type: "22",
  //           target: "21",
  //         },
  //         {
  //           id: "47",
  //           type: "23",
  //           target: "11",
  //         },
  //         {
  //           id: "46",
  //           type: "23",
  //           target: "12",
  //         },
  //         {
  //           id: "39",
  //           type: "23",
  //           target: "16",
  //         },
  //         {
  //           id: "40",
  //           type: "23",
  //           target: "17",
  //         },
  //         {
  //           id: "41",
  //           type: "23",
  //           target: "18",
  //         },
  //         {
  //           id: "42",
  //           type: "23",
  //           target: "19",
  //         },
  //         {
  //           id: "43",
  //           type: "23",
  //           target: "20",
  //         },
  //         {
  //           id: "44",
  //           type: "23",
  //           target: "21",
  //         },
  //         {
  //           id: "45",
  //           type: "23",
  //           target: "22",
  //         },
  //         {
  //           id: null,
  //           type: "24",
  //           target: "11",
  //         },
  //         {
  //           id: "48",
  //           type: "24",
  //           target: "23",
  //         },
  //         {
  //           id: "52",
  //           type: "25",
  //           target: "11",
  //         },
  //         {
  //           id: "51",
  //           type: "25",
  //           target: "23",
  //         },
  //         {
  //           id: "50",
  //           type: "25",
  //           target: "24",
  //         },
  //         {
  //           id: null,
  //           type: "26",
  //           target: "11",
  //         },
  //         {
  //           id: null,
  //           type: "26",
  //           target: "16",
  //         },
  //         {
  //           id: "53",
  //           type: "26",
  //           target: "24",
  //         },
  //         {
  //           id: "56",
  //           type: "26",
  //           target: "25",
  //         },
  //         {
  //           id: "57",
  //           type: "27",
  //           target: "11",
  //         },
  //         {
  //           id: "58",
  //           type: "27",
  //           target: "23",
  //         },
  //         {
  //           id: null,
  //           type: "27",
  //           target: "24",
  //         },
  //         {
  //           id: "59",
  //           type: "27",
  //           target: "25",
  //         },
  //         {
  //           id: "61",
  //           type: "27",
  //           target: "26",
  //         },
  //         {
  //           id: "62",
  //           type: "28",
  //           target: "11",
  //         },
  //         {
  //           id: "63",
  //           type: "28",
  //           target: "27",
  //         },
  //         {
  //           id: "66",
  //           type: "29",
  //           target: "11",
  //         },
  //         {
  //           id: "64",
  //           type: "29",
  //           target: "23",
  //         },
  //         {
  //           id: "65",
  //           type: "29",
  //           target: "27",
  //         },
  //         {
  //           id: "67",
  //           type: "30",
  //           target: "23",
  //         },
  //         {
  //           id: null,
  //           type: "31",
  //           target: "11",
  //         },
  //         {
  //           id: null,
  //           type: "31",
  //           target: "23",
  //         },
  //         {
  //           id: null,
  //           type: "31",
  //           target: "27",
  //         },
  //         {
  //           id: "68",
  //           type: "31",
  //           target: "30",
  //         },
  //         {
  //           id: "72",
  //           type: "32",
  //           target: "11",
  //         },
  //         {
  //           id: "73",
  //           type: "33",
  //           target: "11",
  //         },
  //         {
  //           id: "74",
  //           type: "33",
  //           target: "27",
  //         },
  //         {
  //           id: "75",
  //           type: "34",
  //           target: "11",
  //         },
  //         {
  //           id: "76",
  //           type: "34",
  //           target: "29",
  //         },
  //         {
  //           id: "77",
  //           type: "35",
  //           target: "11",
  //         },
  //         {
  //           id: null,
  //           type: "35",
  //           target: "29",
  //         },
  //         {
  //           id: "78",
  //           type: "35",
  //           target: "34",
  //         },
  //         {
  //           id: "82",
  //           type: "36",
  //           target: "11",
  //         },
  //         {
  //           id: "83",
  //           type: "36",
  //           target: "29",
  //         },
  //         {
  //           id: "80",
  //           type: "36",
  //           target: "34",
  //         },
  //         {
  //           id: "81",
  //           type: "36",
  //           target: "35",
  //         },
  //         {
  //           id: "87",
  //           type: "37",
  //           target: "11",
  //         },
  //         {
  //           id: "88",
  //           type: "37",
  //           target: "29",
  //         },
  //         {
  //           id: "84",
  //           type: "37",
  //           target: "34",
  //         },
  //         {
  //           id: "85",
  //           type: "37",
  //           target: "35",
  //         },
  //         {
  //           id: "86",
  //           type: "37",
  //           target: "36",
  //         },
  //         {
  //           id: "93",
  //           type: "38",
  //           target: "11",
  //         },
  //         {
  //           id: "94",
  //           type: "38",
  //           target: "29",
  //         },
  //         {
  //           id: "89",
  //           type: "38",
  //           target: "34",
  //         },
  //         {
  //           id: "90",
  //           type: "38",
  //           target: "35",
  //         },
  //         {
  //           id: "91",
  //           type: "38",
  //           target: "36",
  //         },
  //         {
  //           id: "92",
  //           type: "38",
  //           target: "37",
  //         },
  //         {
  //           id: "95",
  //           type: "39",
  //           target: "25",
  //         },
  //         {
  //           id: "96",
  //           type: "40",
  //           target: "25",
  //         },
  //         {
  //           id: "97",
  //           type: "41",
  //           target: "24",
  //         },
  //         {
  //           id: "98",
  //           type: "41",
  //           target: "25",
  //         },
  //         {
  //           id: "101",
  //           type: "42",
  //           target: "24",
  //         },
  //         {
  //           id: "100",
  //           type: "42",
  //           target: "25",
  //         },
  //         {
  //           id: "99",
  //           type: "42",
  //           target: "41",
  //         },
  //         {
  //           id: "102",
  //           type: "43",
  //           target: "11",
  //         },
  //         {
  //           id: "103",
  //           type: "43",
  //           target: "26",
  //         },
  //         {
  //           id: "104",
  //           type: "43",
  //           target: "27",
  //         },
  //         {
  //           id: null,
  //           type: "44",
  //           target: "11",
  //         },
  //         {
  //           id: "105",
  //           type: "44",
  //           target: "28",
  //         },
  //         {
  //           id: "107",
  //           type: "45",
  //           target: "28",
  //         },
  //         {
  //           id: "108",
  //           type: "47",
  //           target: "46",
  //         },
  //         {
  //           id: "112",
  //           type: "48",
  //           target: "11",
  //         },
  //         {
  //           id: "110",
  //           type: "48",
  //           target: "25",
  //         },
  //         {
  //           id: "111",
  //           type: "48",
  //           target: "27",
  //         },
  //         {
  //           id: "109",
  //           type: "48",
  //           target: "47",
  //         },
  //         {
  //           id: null,
  //           type: "49",
  //           target: "11",
  //         },
  //         {
  //           id: "113",
  //           type: "49",
  //           target: "26",
  //         },
  //         {
  //           id: null,
  //           type: "50",
  //           target: "24",
  //         },
  //         {
  //           id: "115",
  //           type: "50",
  //           target: "49",
  //         },
  //         {
  //           id: "119",
  //           type: "51",
  //           target: "11",
  //         },
  //         {
  //           id: "118",
  //           type: "51",
  //           target: "26",
  //         },
  //         {
  //           id: "117",
  //           type: "51",
  //           target: "49",
  //         },
  //         {
  //           id: null,
  //           type: "52",
  //           target: "39",
  //         },
  //         {
  //           id: "120",
  //           type: "52",
  //           target: "51",
  //         },
  //         {
  //           id: "122",
  //           type: "53",
  //           target: "51",
  //         },
  //         {
  //           id: "125",
  //           type: "54",
  //           target: "26",
  //         },
  //         {
  //           id: "124",
  //           type: "54",
  //           target: "49",
  //         },
  //         {
  //           id: "123",
  //           type: "54",
  //           target: "51",
  //         },
  //         {
  //           id: "131",
  //           type: "55",
  //           target: "11",
  //         },
  //         {
  //           id: "132",
  //           type: "55",
  //           target: "16",
  //         },
  //         {
  //           id: "133",
  //           type: "55",
  //           target: "25",
  //         },
  //         {
  //           id: null,
  //           type: "55",
  //           target: "26",
  //         },
  //         {
  //           id: "128",
  //           type: "55",
  //           target: "39",
  //         },
  //         {
  //           id: "134",
  //           type: "55",
  //           target: "41",
  //         },
  //         {
  //           id: "135",
  //           type: "55",
  //           target: "48",
  //         },
  //         {
  //           id: "127",
  //           type: "55",
  //           target: "49",
  //         },
  //         {
  //           id: "126",
  //           type: "55",
  //           target: "51",
  //         },
  //         {
  //           id: "129",
  //           type: "55",
  //           target: "54",
  //         },
  //         {
  //           id: "136",
  //           type: "56",
  //           target: "49",
  //         },
  //         {
  //           id: "137",
  //           type: "56",
  //           target: "55",
  //         },
  //         {
  //           id: null,
  //           type: "57",
  //           target: "41",
  //         },
  //         {
  //           id: null,
  //           type: "57",
  //           target: "48",
  //         },
  //         {
  //           id: "138",
  //           type: "57",
  //           target: "55",
  //         },
  //         {
  //           id: "145",
  //           type: "58",
  //           target: "11",
  //         },
  //         {
  //           id: null,
  //           type: "58",
  //           target: "27",
  //         },
  //         {
  //           id: "142",
  //           type: "58",
  //           target: "48",
  //         },
  //         {
  //           id: "141",
  //           type: "58",
  //           target: "55",
  //         },
  //         {
  //           id: "144",
  //           type: "58",
  //           target: "57",
  //         },
  //         {
  //           id: "148",
  //           type: "59",
  //           target: "48",
  //         },
  //         {
  //           id: "147",
  //           type: "59",
  //           target: "55",
  //         },
  //         {
  //           id: null,
  //           type: "59",
  //           target: "57",
  //         },
  //         {
  //           id: "146",
  //           type: "59",
  //           target: "58",
  //         },
  //         {
  //           id: "150",
  //           type: "60",
  //           target: "48",
  //         },
  //         {
  //           id: "151",
  //           type: "60",
  //           target: "58",
  //         },
  //         {
  //           id: "152",
  //           type: "60",
  //           target: "59",
  //         },
  //         {
  //           id: "153",
  //           type: "61",
  //           target: "48",
  //         },
  //         {
  //           id: "158",
  //           type: "61",
  //           target: "55",
  //         },
  //         {
  //           id: "157",
  //           type: "61",
  //           target: "57",
  //         },
  //         {
  //           id: "154",
  //           type: "61",
  //           target: "58",
  //         },
  //         {
  //           id: "156",
  //           type: "61",
  //           target: "59",
  //         },
  //         {
  //           id: "155",
  //           type: "61",
  //           target: "60",
  //         },
  //         {
  //           id: "164",
  //           type: "62",
  //           target: "41",
  //         },
  //         {
  //           id: "162",
  //           type: "62",
  //           target: "48",
  //         },
  //         {
  //           id: "159",
  //           type: "62",
  //           target: "55",
  //         },
  //         {
  //           id: null,
  //           type: "62",
  //           target: "57",
  //         },
  //         {
  //           id: "160",
  //           type: "62",
  //           target: "58",
  //         },
  //         {
  //           id: "161",
  //           type: "62",
  //           target: "59",
  //         },
  //         {
  //           id: null,
  //           type: "62",
  //           target: "60",
  //         },
  //         {
  //           id: "165",
  //           type: "62",
  //           target: "61",
  //         },
  //         {
  //           id: null,
  //           type: "63",
  //           target: "48",
  //         },
  //         {
  //           id: "174",
  //           type: "63",
  //           target: "55",
  //         },
  //         {
  //           id: null,
  //           type: "63",
  //           target: "57",
  //         },
  //         {
  //           id: null,
  //           type: "63",
  //           target: "58",
  //         },
  //         {
  //           id: "167",
  //           type: "63",
  //           target: "59",
  //         },
  //         {
  //           id: null,
  //           type: "63",
  //           target: "60",
  //         },
  //         {
  //           id: "172",
  //           type: "63",
  //           target: "61",
  //         },
  //         {
  //           id: "169",
  //           type: "63",
  //           target: "62",
  //         },
  //         {
  //           id: "184",
  //           type: "64",
  //           target: "11",
  //         },
  //         {
  //           id: null,
  //           type: "64",
  //           target: "48",
  //         },
  //         {
  //           id: "175",
  //           type: "64",
  //           target: "55",
  //         },
  //         {
  //           id: "183",
  //           type: "64",
  //           target: "57",
  //         },
  //         {
  //           id: "179",
  //           type: "64",
  //           target: "58",
  //         },
  //         {
  //           id: "182",
  //           type: "64",
  //           target: "59",
  //         },
  //         {
  //           id: "181",
  //           type: "64",
  //           target: "60",
  //         },
  //         {
  //           id: "180",
  //           type: "64",
  //           target: "61",
  //         },
  //         {
  //           id: "176",
  //           type: "64",
  //           target: "62",
  //         },
  //         {
  //           id: "178",
  //           type: "64",
  //           target: "63",
  //         },
  //         {
  //           id: "187",
  //           type: "65",
  //           target: "48",
  //         },
  //         {
  //           id: "194",
  //           type: "65",
  //           target: "55",
  //         },
  //         {
  //           id: "193",
  //           type: "65",
  //           target: "57",
  //         },
  //         {
  //           id: null,
  //           type: "65",
  //           target: "58",
  //         },
  //         {
  //           id: "192",
  //           type: "65",
  //           target: "59",
  //         },
  //         {
  //           id: null,
  //           type: "65",
  //           target: "60",
  //         },
  //         {
  //           id: "190",
  //           type: "65",
  //           target: "61",
  //         },
  //         {
  //           id: "188",
  //           type: "65",
  //           target: "62",
  //         },
  //         {
  //           id: "185",
  //           type: "65",
  //           target: "63",
  //         },
  //         {
  //           id: "186",
  //           type: "65",
  //           target: "64",
  //         },
  //         {
  //           id: "200",
  //           type: "66",
  //           target: "48",
  //         },
  //         {
  //           id: "196",
  //           type: "66",
  //           target: "58",
  //         },
  //         {
  //           id: "197",
  //           type: "66",
  //           target: "59",
  //         },
  //         {
  //           id: "203",
  //           type: "66",
  //           target: "60",
  //         },
  //         {
  //           id: "202",
  //           type: "66",
  //           target: "61",
  //         },
  //         {
  //           id: "198",
  //           type: "66",
  //           target: "62",
  //         },
  //         {
  //           id: "201",
  //           type: "66",
  //           target: "63",
  //         },
  //         {
  //           id: "195",
  //           type: "66",
  //           target: "64",
  //         },
  //         {
  //           id: "199",
  //           type: "66",
  //           target: "65",
  //         },
  //         {
  //           id: "204",
  //           type: "67",
  //           target: "57",
  //         },
  //         {
  //           id: null,
  //           type: "68",
  //           target: "11",
  //         },
  //         {
  //           id: null,
  //           type: "68",
  //           target: "24",
  //         },
  //         {
  //           id: "205",
  //           type: "68",
  //           target: "25",
  //         },
  //         {
  //           id: "208",
  //           type: "68",
  //           target: "27",
  //         },
  //         {
  //           id: null,
  //           type: "68",
  //           target: "41",
  //         },
  //         {
  //           id: "209",
  //           type: "68",
  //           target: "48",
  //         },
  //         {
  //           id: "213",
  //           type: "69",
  //           target: "11",
  //         },
  //         {
  //           id: "214",
  //           type: "69",
  //           target: "24",
  //         },
  //         {
  //           id: "211",
  //           type: "69",
  //           target: "25",
  //         },
  //         {
  //           id: null,
  //           type: "69",
  //           target: "27",
  //         },
  //         {
  //           id: "217",
  //           type: "69",
  //           target: "41",
  //         },
  //         {
  //           id: "216",
  //           type: "69",
  //           target: "48",
  //         },
  //         {
  //           id: "212",
  //           type: "69",
  //           target: "68",
  //         },
  //         {
  //           id: "221",
  //           type: "70",
  //           target: "11",
  //         },
  //         {
  //           id: "222",
  //           type: "70",
  //           target: "24",
  //         },
  //         {
  //           id: "218",
  //           type: "70",
  //           target: "25",
  //         },
  //         {
  //           id: "223",
  //           type: "70",
  //           target: "27",
  //         },
  //         {
  //           id: "224",
  //           type: "70",
  //           target: "41",
  //         },
  //         {
  //           id: "225",
  //           type: "70",
  //           target: "58",
  //         },
  //         {
  //           id: "220",
  //           type: "70",
  //           target: "68",
  //         },
  //         {
  //           id: "219",
  //           type: "70",
  //           target: "69",
  //         },
  //         {
  //           id: "230",
  //           type: "71",
  //           target: "11",
  //         },
  //         {
  //           id: "233",
  //           type: "71",
  //           target: "25",
  //         },
  //         {
  //           id: "226",
  //           type: "71",
  //           target: "27",
  //         },
  //         {
  //           id: "232",
  //           type: "71",
  //           target: "41",
  //         },
  //         {
  //           id: null,
  //           type: "71",
  //           target: "48",
  //         },
  //         {
  //           id: "228",
  //           type: "71",
  //           target: "68",
  //         },
  //         {
  //           id: "227",
  //           type: "71",
  //           target: "69",
  //         },
  //         {
  //           id: "229",
  //           type: "71",
  //           target: "70",
  //         },
  //         {
  //           id: "236",
  //           type: "72",
  //           target: "11",
  //         },
  //         {
  //           id: "234",
  //           type: "72",
  //           target: "26",
  //         },
  //         {
  //           id: "235",
  //           type: "72",
  //           target: "27",
  //         },
  //         {
  //           id: "237",
  //           type: "73",
  //           target: "48",
  //         },
  //         {
  //           id: "238",
  //           type: "74",
  //           target: "48",
  //         },
  //         {
  //           id: "239",
  //           type: "74",
  //           target: "73",
  //         },
  //         {
  //           id: "242",
  //           type: "75",
  //           target: "25",
  //         },
  //         {
  //           id: "244",
  //           type: "75",
  //           target: "41",
  //         },
  //         {
  //           id: null,
  //           type: "75",
  //           target: "48",
  //         },
  //         {
  //           id: "241",
  //           type: "75",
  //           target: "68",
  //         },
  //         {
  //           id: "240",
  //           type: "75",
  //           target: "69",
  //         },
  //         {
  //           id: "245",
  //           type: "75",
  //           target: "70",
  //         },
  //         {
  //           id: "246",
  //           type: "75",
  //           target: "71",
  //         },
  //         {
  //           id: "252",
  //           type: "76",
  //           target: "48",
  //         },
  //         {
  //           id: "253",
  //           type: "76",
  //           target: "58",
  //         },
  //         {
  //           id: "251",
  //           type: "76",
  //           target: "62",
  //         },
  //         {
  //           id: "250",
  //           type: "76",
  //           target: "63",
  //         },
  //         {
  //           id: "247",
  //           type: "76",
  //           target: "64",
  //         },
  //         {
  //           id: "248",
  //           type: "76",
  //           target: "65",
  //         },
  //         {
  //           id: "249",
  //           type: "76",
  //           target: "66",
  //         },
  //       ],
  //       categories: [
  //         {
  //           name: "类目0",
  //         },
  //         {
  //           name: "类目1",
  //         },
  //         {
  //           name: "类目2",
  //         },
  //         {
  //           name: "类目3",
  //         },
  //         {
  //           name: "类目4",
  //         },
  //         {
  //           name: "类目5",
  //         },
  //         {
  //           name: "类目6",
  //         },
  //         {
  //           name: "类目7",
  //         },
  //         {
  //           name: "类目8",
  //         },
  //       ],
  //     },
  //   ],
  // };
  return (
    <Primitive error={error} ready={!!data}>
      {options && <Chart options={options} />}
    </Primitive>
  );
};

export default {
  type: "graph",
  component: Graph,
};
