CREATE TABLE public.t (id int) PARTITION BY HASH (id);
CREATE TABLE public.t_0 PARTITION OF public.t FOR VALUES WITH (MODULUS 2, REMAINDER 0);
CREATE TABLE public.t_1 PARTITION OF public.t FOR VALUES WITH (MODULUS 2, REMAINDER 1);
INSERT INTO public.t SELECT g FROM generate_series(1,10) g;
