name: ">>>> Docker testing"
on: push
jobs:

  acceptance_test:
    name: Acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: uname
        run: uname -a

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: docker?
        run: |
          docker info

      - name: build an image
        run: |
          docker build -t sp dockertesting/debian
          docker images

      - name: run test suite in a container
        run: |
          docker run --name steampipe-test `docker images -q sp`
