name: ">>>> Docker testing"
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: turbot/steampipe:latest
    steps:
      - run: steampipe -v
      - run: steampipe -h
      - run: steampipe query "select 1"