name: ">>>> Docker testing"
on: push
jobs:
  first-job:
    name: Check steampipe version
    runs-on: ubuntu-latest
    container: turbot/steampipe:latest
    steps:
      - name: Check version
        run: steampipe -v

      - name: Query
        run: steampipe query "select 1"

  acceptance_test:
    name: Acceptance tests
    needs: first-job
    runs-on: ubuntu-latest
    container: "ubuntu:latest"
    steps:
      - name: uname
        run: uname -a

      - name: Checkout
        uses: actions/checkout@v3

      - name: ls
        run: |
          ls -al

      - name: install git
        run: |
          apt update -y
          apt upgrade -y
          apt install -y git sudo wget curl vim

      # - name: Checkout submodules
      #   run: |
      #     ls
      #     git submodule update --init
      #     git submodule update --recursive

      - name: install steampipe
        run: |
          ./install.sh v0.14.6
          adduser sp -y
          su - sp
          steampipe query "select 1"

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Set PATH
        run: |
          pwd
          ls -al
          echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/libexec" >> $GITHUB_ENV

      - name: Install DB
        continue-on-error: false
        run: |
          steampipe service start
          steampipe service stop

      - name: Run Test Suite
        id: run-test-suite
        timeout-minutes: 15
        continue-on-error: true
        run: |
          chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
          $GITHUB_WORKSPACE/tests/acceptance/run.sh
          steampipe service stop --force
      
  #     - name: Save Test Suite Logs
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: test-logs
  #         path: ~/.steampipe/logs
  #         if-no-files-found: error
      
  #     # This job checks whether the test suite has passed or not.
  #     # Since the exit_code is set only when the bats test suite pass, so we have added the if-conditional block 
  #     - name: Check Test Passed/Failed
  #       continue-on-error: false
  #       run: |
  #         if [ ${{ steps.run-test-suite.outputs.exit_code }} -eq 0 ]; then
  #           exit 0
  #         else
  #           exit 1
  #         fi

  # clean_up:
  #   name: Clean Up
  #   needs: acceptance_test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clean up Test Suite Logs
  #       uses: geekyeggo/delete-artifact@v1
  #       with:
  #         name: test-logs
  #         failOnError: true