name: GCloud Artifact Registry List test
on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT_ID: steampipe
  CORE_REPO: us-docker.pkg.dev/steampipe/steampipe
  ORG: turbot
  ASSET_IMAGE_NAME: assets
  CONFIG_SCHEMA_VERSION: "2020-11-18"
  VERSION: v0.1.0
  STEAMPIPE_UPDATE_CHECK: false

jobs:
  goreleaser:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trim asset version prefix and Validate
        run: |-
          echo $VERSION
          trim=${VERSION#"v"}
          echo $trim
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
            echo "Version OK: $VERSION"
          else
            echo "Invalid version: $VERSION"
            exit 1
          fi
          echo "VERSION=${trim}" >> $GITHUB_ENV

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          service_account_key: ${{ secrets.GCP_GITHUB_ACTION_PUSH_ARTIFACTS }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Verify
        run: |-
          [ gcloud beta artifacts docker tags list $CORE_REPO/$ASSET_IMAGE_NAME  --project $PROJECT_ID  --format=json | jq 'map(select(.tag | endswith("$VERSION"))) | length' -eq 0 ]
      
      - name: NEXT
        run: |-
          echo "DONE"
