name: Update brew formula
on: push

env:
  GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  update_homebrew_tap:  
    name: Update homebrew-tap formula
    runs-on: ubuntu-latest
    steps:
      - name: Create and merge pull request
        run: |
          git clone https://github.com/turbot/homebrew-tap.git
          git config --global --add safe.directory /home/runner/work/steampipe/steampipe/homebrew-tap
          git config --global init.defaultBranch main
          git init
          git fetch
          cd homebrew-tap

          pr_link=$(gh pr create --base dev --head bump --title "Brew formula update for steampipe" --body "Update formula")

          gh pr merge $pr_link --squash
          