name: Update brew formula
on: push

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update_homebrew_tap:  
    name: Update homebrew-tap formula
    runs-on: ubuntu-latest
    steps:
      - name: Create and merge pull request
        run: |
          git clone https://github.com/turbot/homebrew-tap.git
          git config --global --add safe.directory /home/runner/work/homebrew-tap/homebrew-tap
          git config --global init.defaultBranch main
          git init
          git fetch
          cd homebrew-tap

          gh pr create --base bump_formula --head bump --title "Brew formula update for steampipe version ${{ github.event.inputs.release }}" --body "update formula"